### ISSUE TITLE
Not working on 2023.3

### ISSUE THREAD

**Issue by legendmohe** [wisetime-io/intellij-branch-in-window-title#17]
![image](https://github.com/wisetime-io/intellij-branch-in-window-title/assets/1665771/0fcfe5ba-e787-44ef-96da-d1114620ab7d)

**Comment by legendmohe** [comment]
Android Studio Ladybug | 2024.1.3 Canary 3
Not working

**Comment by sukolenvo** [comment]
I've tested plugin with Android Studio 2024.1.3 Canary 3. And it works as expected - window title is updated and includes branch name. Note that by default IDE and Android Studio doesn't show window title toolbar (has to be enabled in settings and instructions vary by OS and version of IDE).

Here are results of my test (linux):

```bash
$ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x3a00054 "Signal – build.gradle.kts my-new-branch"
```

Settings -> Appearance and Behaviour -> Appearance -> Disable "Merge main menu with window title"
![image](https://github.com/user-attachments/assets/d04ad388-7862-4ae9-b36f-b7cf43d9932d)
