### ISSUE TITLE
Doesn't apply on windows

### ISSUE THREAD

**Issue by fluffynuts** [wisetime-io/intellij-branch-in-window-title#3]
Unfortunately, this plugin doesn't seem to apply on Windows, probably because the Windows variants of IntelliJ-based IDEs don't use the OS-level window decorations -- rather, like Visual Studio, they are incorporated into the menu bar:

![image](https://user-images.githubusercontent.com/4669340/100056454-60a91880-2e2e-11eb-9377-32f452be211c.png)

Here you can see that I'm on `master`, but nothing is reflected in the "title bar" of the application. The screenshots at https://plugins.jetbrains.com/plugin/9675-branch-in-window-title show for OSX and what looks like GNOME? Either way, the title-bars there are not part of the application: they are window decorations provided by the windowing manager. Many Windows apps are following the style of hiding the native window decorations and "collapsing" the title-bar into the top UI element of the app (eg Firefox / Chrome put tabs up there, IntelliJ-based IDEs have the menu bar up there).

I'd really like to see the branch name in the title on Windows -- would help me to catch myself before making a mistake like committing to the wrong branch (:

**Comment by vyshane** [comment]
This is a tough one, unfortunately, and you have hit the nail on the head:

> Many Windows apps are following the style of hiding the native window decorations and "collapsing" the title-bar into the top UI element of the app (eg Firefox / Chrome put tabs up there, IntelliJ-based IDEs have the menu bar up there).

While the `intellij-branch-in-window-title` plugin is able to successfully set the window title, and the window title does get picked up correctly by [WiseTime](https://wisetime.com), that information is not actually rendered on screen by the IDE as it uses a frameless window.

We have looked into whether we could render the title next to the menu per your screenshot. However, there is currently no public API to do so. If you know a way to remedy this issue, please feel free to re-open. Thanks for reporting.
