### ISSUE TITLE
Branch name is being appended to window title

### ISSUE THREAD

**Issue by tramdeholl** [wisetime-io/intellij-branch-in-window-title#8]
Each time I reopen a project or switch branches, the current branch gets appended to the window title. Where can I clear this out in the meantime?

I'm currently using IntelliJ 2022.1. This was not an issue in the previous version.

![image](https://user-images.githubusercontent.com/82117396/164085250-8f2cdcbf-5e2f-42af-8659-b1d2c3792a27.png)

**Comment by tom-haines** [comment]
I am unable to reproduce this on IntelliJ IDEA 2022.1 (Mac).

@tramdeholl 
In the screenshot, it looks to be the same tag name that is duplicated.  Queries:

i. can you attach screenshot of window title appearance when you switch to different branches?

ii. can you paste here info from About IntelliJ idea -> copy?

iii. can you replicate this in a fresh repo (create a sample project, git init, git checkout -b foo1 etc) and if yes, attach the zip file of that project you created?

**Comment by vince-kal** [comment]
This same issue is happening to me also. It seems to compound over time, so a fresh project the branch is only there once, but if I have the same project open for hours or days the title gradually gets longer, which makes me think is it happening on auto git fetch or something like that. This does seem a pretty new problem over the last few weeks at some point, as never had any issues using the plugin for last 3 years.
![Screenshot 2022-04-21 at 12 23 54](https://user-images.githubusercontent.com/81644121/164448408-68e41d37-acf5-47a9-a070-484708ea7a27.png)
Disabling the plugin makes no difference, the long title just stays there.

About:
`
PhpStorm 2022.1
Build #PS-221.5080.224, built on April 13, 2022
Licensed to ***********
Subscription is active until April 25, 2022.
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 3500M
Cores: 16
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.intellij.ideolog (203.0.28.1)
    com.alayouni.ansiHighlight (1.2.4)
    zielu.gittoolbox (212.8.9)
    mobi.hsz.idea.gitignore (4.4.0)
    de.espend.idea.php.annotation (8.2.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.221)
    de.espend.idea.laravel (0.15.4)
    com.mallowigi (62.0.0)
    ru.adelf.idea.dotenv (2022.1)
`

**Comment by sukolenvo** [comment]
Do you have enabled `Append VCS branch name to project name (Experimental)` in preferences? If so can you try disable it (its primary use for Windows OS where title rendering implemented completely different way)?
![image](https://user-images.githubusercontent.com/25821770/164580790-c073ef8f-f9e1-4886-a3c5-05fa83796e03.png)

**Comment by vince-kal** [comment]
No, I do not have that setting available

![Screenshot 2022-04-22 at 08 01 51](https://user-images.githubusercontent.com/81644121/164622506-6b59a7c5-23a2-4370-ac5a-6ea072d665da.png)

**Comment by sukolenvo** [comment]
You probably removed plugin? Its not on the list from your previous message
```
Non-Bundled Plugins:
    com.intellij.ideolog (203.0.28.1)
    com.alayouni.ansiHighlight (1.2.4)
    zielu.gittoolbox (212.8.9)
    mobi.hsz.idea.gitignore (4.4.0)
    de.espend.idea.php.annotation (8.2.0)
    fr.adrienbrault.idea.symfony2plugin (2022.1.221)
    de.espend.idea.laravel (0.15.4)
    com.mallowigi (62.0.0)
    ru.adelf.idea.dotenv (2022.1)
```

**Comment by vince-kal** [comment]
Oh, sorry, yes I had temporarilly disabled the plugin as a debugging excercise.

I've re-enabled the plugin and the Branch Name settings reappeared. Both of the options to append were selected. (these must have been defaults, because I'm pretty sure I havent been in there to change them) I have disabled the option to append to project name. I presume I should leave the other one enabled to append to window title?

I'll see how this goes for a few days, and also test on some new projects.

Do you know of any way I can remove all of the appended branch names from the problem project - is there a setting or even a config file somewhere?

**Comment by sukolenvo** [comment]
You can rename project via: `File > Project Structure > Project > Project Name`
Thanks helping identify issue

**Comment by vince-kal** [comment]
Awesome, thanks for your help. It was literally just `File > Rename Project...` for me.

**Comment by tramdeholl** [comment]
@sukolenvo Thanks for the help. I also had that option checked but it was enabled by default. I didn't notice a problem until I upgraded to Intellij IDEA 2022.1. I unchecked that option, renamed the project and all is well.
