### ISSUE TITLE
Branch name added into existing window title instead of replacing previous branch name

### ISSUE THREAD

**Issue by AllenJB** [wisetime-io/intellij-branch-in-window-title#9]
When switching branches (and I think some other operations due to the duplication I'm seeing, even for branches that have not yet been pushed or committed to) in PHPStorm 2022.2, on Windows 10 with merged min menu and title bar disabled, the branch name is appended into the existing title, rather than replacing the previous branch name, resulting in the window title looking something like:
Project Name [branch_1] [master] [master] [master] [branch_2] [branch_2] - ...\Current\File\Path

The bugged title appears to persist across restarts of PHPStorm

**Comment by sukolenvo** [comment]
Hi @AllenJB , thank you for reporting. Its known issue on Windows. You can rename project manually to remove suffix. I don't know when I will have time to look into this, I will keep you updated on any progress.

**Comment by ChanoAndersen** [comment]
It's a problem on macOS as well.

**Comment by nordfalk** [comment]
Try again ....
![image](https://github.com/wisetime-io/intellij-branch-in-window-title/assets/1143272/5fd84e6e-774d-4270-aac3-0562cddc9d8c)

Android Studio Iguana | 2023.2.1 Canary 14
Build #AI-232.10227.8.2321.11110254, built on November 16, 2023
Runtime version: 17.0.9+0-17.0.9b1000.46-11084592 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.0-37-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.copilot (1.4.4.3955)
    com.intellij.marketplace (232.10227.13)
    PythonCore (232.10203.2)
    io.wisetime.plugins.window.branch (1.1.0)

Current Desktop: ubuntu:GNOME

**Comment by sukolenvo** [comment]
Hi @nordfalk , would you be able to try this build? https://cdn.wisetime.com/branch-window-title-1.1.0.zip
To install plugin from file please follow: https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by nordfalk** [comment]
Hi, I 
* removed all .idea/.name files to get rid of the custom project names, and
* installed  https://cdn.wisetime.com/branch-window-title-1.1.0.zip 

And it works fine now, thank you :-)

**Comment by allanlaal** [comment]
1.1.0 (from Jetbrains's store) did not have this fix

**Comment by sukolenvo** [comment]
I believe latest version 2.0.0 don't have this problem. Window title integration has been re implemented.
